/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConfigModel } from './ConfigModel';
import {
    ConfigModelFromJSON,
    ConfigModelFromJSONTyped,
    ConfigModelToJSON,
    ConfigModelToJSONTyped,
} from './ConfigModel';

/**
 * Global configuration snapshot for frontend.
 * @export
 * @interface GlobalConfig
 */
export interface GlobalConfig {
    /**
     * Current default model key
     * @type {string}
     * @memberof GlobalConfig
     */
    defaultModel: string;
    /**
     * Current default thinking mode from `[thinking].enabled`
     * (falls back to deprecated top-level `default_thinking`, then CLI default true).
     * @type {boolean}
     * @memberof GlobalConfig
     */
    defaultThinking: boolean;
    /** Active value from [thinking].effort. */
    thinkingEffort: string;
    /**
     * Current default plan mode
     * @type {boolean}
     * @memberof GlobalConfig
     */
    defaultPlanMode: boolean;
    /**
     * Current default permission mode from Kimi Code
     * @type {string}
     * @memberof GlobalConfig
     */
    defaultPermissionMode: string;
    /**
     * All configured models
     * @type {Array<ConfigModel>}
     * @memberof GlobalConfig
     */
    models: Array<ConfigModel>;
    /** True when KIMI_CODE_EXPERIMENTAL_SECONDARY_MODEL or KIMI_CODE_EXPERIMENTAL_FLAG is set for the Desktop process. */
    secondaryModelExperimentEnabled?: boolean;
    /** Effective secondary model alias (env override wins over [secondary_model].model). */
    secondaryModel?: string | null;
    /** Effective secondary default effort (env override wins over config). */
    secondaryDefaultEffort?: string | null;
    /** Whether [secondary_model].model is set in config.toml (ignoring env override). */
    secondaryModelConfigured?: boolean;
    /** Whether the effective secondary model resolves to a configured [models] entry. */
    secondaryModelValid?: boolean;
    /** True when KIMI_SECONDARY_MODEL env override is active. */
    secondaryModelEnvOverride?: boolean;
    /** True when KIMI_SECONDARY_EFFORT env override is active. */
    secondaryDefaultEffortEnvOverride?: boolean;
}

/**
 * Check if a given object implements the GlobalConfig interface.
 */
export function instanceOfGlobalConfig(value: object): value is GlobalConfig {
    if (!('defaultModel' in value) || value['defaultModel'] === undefined) return false;
    if (!('defaultThinking' in value) || value['defaultThinking'] === undefined) return false;
    if (!('thinkingEffort' in value) || value['thinkingEffort'] === undefined) return false;
    if (!('defaultPlanMode' in value) || value['defaultPlanMode'] === undefined) return false;
    if (!('defaultPermissionMode' in value) || value['defaultPermissionMode'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    return true;
}

export function GlobalConfigFromJSON(json: any): GlobalConfig {
    return GlobalConfigFromJSONTyped(json, false);
}

export function GlobalConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModel': json['default_model'],
        'defaultThinking': json['default_thinking'],
        'thinkingEffort': json['thinking_effort'] ?? '',
        'defaultPlanMode': Boolean(json['default_plan_mode']),
        'defaultPermissionMode': json['default_permission_mode'] ?? 'manual',
        'models': ((json['models'] as Array<any>).map(ConfigModelFromJSON)),
        'secondaryModelExperimentEnabled': Boolean(json['secondary_model_experiment_enabled']),
        'secondaryModel': json['secondary_model'] ?? null,
        'secondaryDefaultEffort': json['secondary_default_effort'] ?? null,
        'secondaryModelConfigured': Boolean(json['secondary_model_configured']),
        'secondaryModelValid': json['secondary_model_valid'] == null
            ? true
            : Boolean(json['secondary_model_valid']),
        'secondaryModelEnvOverride': Boolean(json['secondary_model_env_override']),
        'secondaryDefaultEffortEnvOverride': Boolean(json['secondary_default_effort_env_override']),
    };
}

export function GlobalConfigToJSON(json: any): GlobalConfig {
    return GlobalConfigToJSONTyped(json, false);
}

export function GlobalConfigToJSONTyped(value?: GlobalConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model': value['defaultModel'],
        'default_thinking': value['defaultThinking'],
        'thinking_effort': value['thinkingEffort'],
        'default_plan_mode': value['defaultPlanMode'],
        'default_permission_mode': value['defaultPermissionMode'],
        'models': ((value['models'] as Array<any>).map(ConfigModelToJSON)),
        'secondary_model_experiment_enabled': value['secondaryModelExperimentEnabled'] ?? false,
        'secondary_model': value['secondaryModel'] ?? null,
        'secondary_default_effort': value['secondaryDefaultEffort'] ?? null,
        'secondary_model_configured': value['secondaryModelConfigured'] ?? false,
        'secondary_model_valid': value['secondaryModelValid'] ?? true,
        'secondary_model_env_override': value['secondaryModelEnvOverride'] ?? false,
        'secondary_default_effort_env_override': value['secondaryDefaultEffortEnvOverride'] ?? false,
    };
}
